version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@3.1.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - eb/setup
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: Front-End Install
          command: |
            npm run fe-install
      - run:
          name: Back-End Install
          command: |
            npm run be-install
      - run:
          name: Front-End Build
          command: |
            npm run fe-build
      - run:
          name: Back-End Build
          command: |
            npm run be-build